#!/usr/bin/env python3
"""从 M5StickS3/cnfont_full_uint32.h 提取本项目所需字符子集。"""
import re
import sys

FULL_H = '/Users/yuzhang/M5StickS3/cnfont_full_uint32.h'
OUTPUT_H = '/Users/yuzhang/M5_VoiceStick/cnfont.h'

# 所有 UI 字符串的合集（中英文 + 标点 + 数字）
UI_TEXT = (
    "按下语音识别"
    "REC AUTO"
    "上传中"
    "已粘贴 未连"
    "失败"
    "WiFi 配置模式"
    "凭证已保存 断线尝试重连 初始就绪"
    "等待连接"
    "录音停止 已录 秒"
    "发送 缓冲 分配 解析 结果"
    "启动广播 文本服务 重启 断开"
    "请输入 WiFi 密码 保存 退出"
    "0123456789"
    "：./()-:!"
    # ASR 输出常见标点
    "，。！？、；""''《》【】…"
    "abcdefghijklmnopqrstuvwxyz"
    "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    # 花费统计 UI
    "本次花费总计清零返回元成功长按短"
)

KEEP = set(UI_TEXT.replace(' ', '').replace('\n', ''))
KEEP.add(' ')  # 保留空格

def main():
    with open(FULL_H, 'r') as f:
        content = f.read()

    m = re.search(r'Bitmaps\[\] PROGMEM = \{(.*?)\};', content, re.DOTALL)
    full_bm = bytes(int(b, 16) for b in re.findall(r'0x([0-9A-Fa-f]{2})', m.group(1)))

    m = re.search(r'Glyphs\[\] PROGMEM = \{(.*?)\};', content, re.DOTALL)
    full_gl_raw = re.findall(r'\{\s*(\d+),\s*(\d+),\s*(\d+),\s*(\d+),\s*(-?\d+),\s*(-?\d+)\s*\}', m.group(1))
    full_gl = [tuple(int(x) for x in g) for g in full_gl_raw]

    m = re.search(r'GFXfont\s+\w+\s+PROGMEM\s*=\s*\{[^}]*?,\s*0x([0-9A-Fa-f]+),\s*0x([0-9A-Fa-f]+),\s*(\d+)\s*\}', content)
    first = int(m.group(1), 16)
    last = int(m.group(2), 16)
    yAdvance = int(m.group(3))

    new_bm = bytearray([0x00])
    new_gl = []
    kept = 0
    missing = []

    for code in range(first, last + 1):
        idx = code - first
        c = chr(code)

        if c in KEEP and idx < len(full_gl):
            offset, w, h, adv, xo, yo = full_gl[idx]
            if w > 1 and h > 1:
                size = ((w + 7) // 8) * h
                bitmap = full_bm[offset:offset + size]
                if any(b != 0 for b in bitmap):
                    new_offset = len(new_bm)
                    new_bm.extend(bitmap)
                    new_gl.append((new_offset, w, h, adv, xo, yo))
                    kept += 1
                    continue
            # 在 KEEP 里但 bitmap 为空（如空格）：保留源 advance
            # 否则会被占位符的 31 替代，导致空格/不可见字符占满宽度
            new_gl.append((0, 1, 1, adv, 0, 0))
            continue

        new_gl.append((0, 1, 1, 31, 0, 0))
        if c in KEEP:
            missing.append(c)

    print(f"保留有效字符: {kept}")
    print(f"Bitmaps: {len(new_bm)}B, Glyphs: {len(new_gl) * 7}B")
    if missing:
        print(f"警告: 完整字体中缺失: {''.join(missing)}", file=sys.stderr)

    header = f"""// Auto-generated by rebuild_cnfont.py
// 从完整字体提取 {kept} 个字符
// Source: LXGWWenKaiLite-Regular.ttf 16pt
// 字体名: cnfont_subset16pt8b

const uint8_t cnfont_subset16pt8bBitmaps[] PROGMEM = {{
"""
    bm_lines = []
    for i in range(0, len(new_bm), 12):
        chunk = new_bm[i:i + 12]
        bm_lines.append("  " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    header += "\n".join(bm_lines) + "\n};\n\n"

    header += "const GFXglyph cnfont_subset16pt8bGlyphs[] PROGMEM = {\n"
    for i, g in enumerate(new_gl):
        offset, w, h, adv, xo, yo = g
        code = first + i
        comment = ""
        if w > 1:
            try:
                comment = f"  // 0x{code:04X} '{chr(code)}'"
            except ValueError:
                comment = f"  // 0x{code:04X}"
        header += f"  {{ {offset:5d}, {w:2d}, {h:2d}, {adv:2d}, {xo:4d}, {yo:4d} }},{comment}\n"
    header += "};\n\n"

    header += (
        "const GFXfont cnfont_subset16pt8b PROGMEM = {\n"
        "  (uint8_t  *)cnfont_subset16pt8bBitmaps,\n"
        "  (GFXglyph *)cnfont_subset16pt8bGlyphs,\n"
        + "  0x" + format(first, 'X') + ", 0x" + format(last, 'X') + ", " + str(yAdvance) + " };\n\n"
        + f"// Approx. {len(new_bm)} + {len(new_gl) * 7} bytes\n"
    )

    with open(OUTPUT_H, 'w') as f:
        f.write(header)
    import os
    print(f"已写入 {OUTPUT_H} ({os.path.getsize(OUTPUT_H)} 字节)")

if __name__ == '__main__':
    main()
